### PR TITLE
Update projects.txt

### PR DESCRIPTION
**Pull request by aricodeine**
added my app repo, the app uses objectbox

### CODE REVIEW

**Comment by ashitaprasad** [comment]
@aricodeine Please update the project readme to include some snapshots and proper description.

**Comment by aricodeine** [comment]
i'll do it soon

**Comment by aricodeine** [comment]
@ashitaprasad updated readme. If any more changes required, let me know

**Comment by ashitaprasad** [comment]
Thanks @aricodeine 👍

**Pull request merged**
